

### Test POST request to upload a file### Test POST request to upload a file
POST http://localhost:3000/api/atoukmat/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczOTUzNjg2MiwiZXhwIjoxNzM5NTQwNDYyfQ.twEzN4C-XF0Ns8int8Yugd8exK8YedznlunLVI0--7Y
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="avatar.png"
Content-Type: image/png

< /Users/atoukmat/goinfre/transbadtrip/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="type"

profilepic
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
GET http://localhost:3000/
Content-Type: application/json

###
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lIjoxNzQxODEyMDUyOTYwLCJ1c2VySWQiOjEsImlhdCI6MTc0MTgxMjA1MiwiZXhwIjoxNzQxODE1NjUyfQ.s0mLVaNrGI1IKndX-fQcpymXss6n8WxGdszjOWCG65M"

### Test POST request to register a new user
POST http://localhost/register
Content-Type: application/json

{
    "login": "aloteefsssiss",
    "email": "aloe3dtfi@hoslda.com",
    "name": "zeb123",
    "password": "passwords1234"
}

### Test POST request to login
POST http://localhost/login
Content-Type: application/json

{
    "email": "aloe3dtfi@hoslda.com",
    "password": "passwords1234"
}

###
POST http://localhost:3000/friends/dddd
Content-Type: application/json

{
    

}
### Test POST request to Google Sign-In (mocked)
POST http://localhost:3000/google-signin
Content-Type: application/json

{
    "email": "googleuser@example.com",
    "name": "Google User",
    "avatar": "googleavatar.png"
}
###

PUT http://localhost:3000/user/aloteefiss
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lIjoxNzQxODEyNzgwNjE2LCJ1c2VySWQiOjEsImlhdCI6MTc0MTgxMjc4MCwiZXhwIjoxNzQxODE2MzgwfQ.qHITZoLON2xXCrRpEyhEvshhJlxh5SbvBYWHFxrvl_g

{
    "new_email" : "alotfffffi@1337.ma",
    "new_name" : "ayoublorrrtfi"
}

### Test GET request to profile (protected route)
GET http://localhost/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lIjoxNzQxODEyMDUyOTYwLCJ1c2VySWQiOjEsImlhdCI6MTc0MTgxMjA1MiwiZXhwIjoxNzQxODE1NjUyfQ.s0mLVaNrGI1IKndX-fQcpymXss6n8WxGdszjOWCG65M
# Content-Type: application/json

### Test 
POST http://localhost/2fa/activate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lIjoxNzQxODMzNTQzNDM0LCJ1c2VySWQiOjEsImlhdCI6MTc0MTgzMzU0MywiZXhwIjoxNzQxODM3MTQzfQ.uQ-vkh2Zgi35Lvw2qCqd28uHV8nlHR6aPLXb6qpfX04

{
    "activate": true
}

### Test 
POST http://localhost/2fa/generate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lIjoxNzQxODMzNTQzNDM0LCJ1c2VySWQiOjEsImlhdCI6MTc0MTgzMzU0MywiZXhwIjoxNzQxODM3MTQzfQ.uQ-vkh2Zgi35Lvw2qCqd28uHV8nlHR6aPLXb6qpfX04

{
    
}
###
POST http://localhost/2fa/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lIjoxNzQxODMzNTQzNDM0LCJ1c2VySWQiOjEsImlhdCI6MTc0MTgzMzU0MywiZXhwIjoxNzQxODM3MTQzfQ.uQ-vkh2Zgi35Lvw2qCqd28uHV8nlHR6aPLXb6qpfX04

{
    "otp": "257263"
}
### Test POST request to cancel friend request
POST http://localhost:3000/friends/cancel
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
    "friendId": "980710"
}

### Test POST request to remove friend
POST http://localhost:3000/friends/remove
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
    "friendId": "12345"
}

### Test POST request to list friends
POST http://localhost:3000/friends/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lIjoxNzQxNDg3OTMzNjI3LCJ1c2VySWQiOjIsImlhdCI6MTc0MTQ4NzkzMywiZXhwIjoxNzQxNDkxNTMzfQ.ItoD249Smb9Eh6Om_zm4Yhg-0UcsOU8JeelvZQXZPz8

{}

### Test POST request to get friend requests
POST http://localhost:3000/friends/requests
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{}

### Test POST request to accept friend request
POST http://localhost:3000/friends/accept
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
    "friendId": "12345"
}

### Test POST request with invalid action
POST http://localhost:3000/friends/invalid_action
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{}

### Test POST request to trigger error
POST http://localhost:3000/friends/error
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{}