networks:
  trans:
    name: trans
volumes:
  uploads:
    driver: local
    driver_opts:
      type: none
      device: /Users/alotfi/uploads
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: /Users/alotfi/database
      o: bind
  files:
    driver: local
    driver_opts:
      type: none
      device: /Users/alotfi/frontfiles
      o: bind
services:
  frontend:
    container_name: frontend
    build: frontend
    depends_on:
      - back
    restart: always
    volumes:
    - files:/files
    networks:
      - trans
  back:
    container_name: back
    build: back
    env_file: back/.env
    restart: always
    volumes:
      - database:/srcs/prisma
      - uploads:/srcs/uploads
    networks:
      - trans
  nginx:
    container_name: nginx 
    build: ./services/nginx
    ports:
      - "443:443"
    env_file: .env
    restart: always
    volumes:
      - uploads:/var/www/uploads/
    networks:
      - trans
