networks:
  trans:
    name: trans
volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /Users/atoukmat/database
      o: bind
services:
  frontend:
    container_name: frontend
    build: frontend
    depends_on:
      - back
    restart: always
    networks:
      - trans
  back:
    container_name: back
    build: back
    env_file: back/.env
    restart: always
    volumes:
      - database:/srcs/prisma/dev.db
    networks:
      - trans
  nginx:
    container_name: nginx 
    build: ./services/nginx
    ports:
      - "443:443"
    env_file: .env
    restart: always
    networks:
      - trans
