
{
  "id": 1,
  "login": "atoukmat",
  "email": "hola@holda.com",
  "name": "zeb123",
  "password": "$2b$10$NZ/PZm7zuBxBx9n4DGQcFePn4zHy2icjNIBvl2/UCWR4CF0qsU1uy",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczOTM4OTIwOSwiZXhwIjoxNzM5MzkyODA5fQ.pN2OHRaK8xe3OwM2fp3_Oclq3aAPkthPiIfsJQd230E"
  

}
 
###
GET http://localhost:3000/
Content-Type: application/json

### Test POST request to register a new user
POST http://localhost:3000/register
Content-Type: application/json

{
    "login": "atoukmat",
    "email": "hola@holda.com",
    "name": "zeb123",
    "password": "passwords123"
}

### Test POST request to login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "hola@holda.com",
    "password": "passwords123"
}

### Test POST request to Google Sign-In (mocked)
POST http://localhost:3000/google-signin
Content-Type: application/json

{
    "email": "googleuser@example.com",
    "name": "Google User",
    "avatar": "googleavatar.png"
}

### Test PUT request to update user
PUT http://localhost:3000/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczOTM2MDI5MSwiZXhwIjoxNzM5MzYzODkxfQ.cS6BIeeMnLlmfAGkICdkcEOprNeKwW2ee9B8tOV56dU

{
    "email": "hola@example.com",
    "name": "howhow",
    "password": "23"
}

###
PUT http://localhost:3000/api/atoukmat/change_password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczOTM3MTMyNCwiZXhwIjoxNzM5Mzc0OTI0fQ.DJFmCyDhkIMB30NDRIQDEWSc0Xm6rwfGTWoP3fG-X8Y

{
    "password": "2343434323"
}

### Test GET request to profile (protected route)
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTczOTM1MzA4MCwiZXhwIjoxNzM5MzU2NjgwfQ.W3tonUOvyEiuvrKYFksN9v8g2wbTSHMb11s-RLpMKlc
# Content-Type: application/json

