
{
  "id": 1,
  "email": "hola@hola.com",
  "name": "zeb123",
  "password": "$2b$10$V829BPBpzRp23NemUb7RF.4aZVMQI2O2xIsGtiWoQe8JKNoCxT/NC",
   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczOTM1NTU1MiwiZXhwIjoxNzM5MzU5MTUyfQ.Q-ElLBNzj9nG5fA1p2-7Umqs4_uPGyt123AJy9OW41o"
}
### salam 
GET http://localhost:3000/
Content-Type: application/json

### Test POST request to register a new user
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "hola@hola.com",
    "name": "zeb123",
    "password": "passwords123"
}

### Test POST request to login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "hola@hola.com",
    "password": "passwords123"
}

### Test POST request to Google Sign-In (mocked)
POST http://localhost:3000/google-signin
Content-Type: application/json

{
    "email": "googleuser@example.com",
    "name": "Google User",
    "avatar": "googleavatar.png"
}

### Test PUT request to update user
PUT http://localhost:3000/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczOTM1NTU1MiwiZXhwIjoxNzM5MzU5MTUyfQ.Q-ElLBNzj9nG5fA1p2-7Umqs4_uPGyt123AJy9OW41o

{
    "email": "hola@example.com",
    "name": "bad trip ",
    "password": "neeeewpassword123"
}

### Test GET request to profile (protected route)
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTczOTM1MzA4MCwiZXhwIjoxNzM5MzU2NjgwfQ.W3tonUOvyEiuvrKYFksN9v8g2wbTSHMb11s-RLpMKlc
# Content-Type: application/json

